import React from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  type: 'terms' | 'privacy' | 'dispute-policy';
  navigate: (path: string) => void;
}

export const LegalPage: React.FC<LegalPageProps> = ({ type, navigate }) => {
  const titles = {
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    'dispute-policy': 'Dispute Resolution & Arbitration Rules',
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      <button
        onClick={() => navigate('/')}
        className="text-slate-500 hover:text-slate-900 text-xs font-semibold flex items-center gap-1.5 transition"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </button>

      <div className="bg-white border border-slate-200 rounded-2xl p-8 sm:p-12 shadow-xs space-y-6 text-sm text-slate-700 leading-relaxed">
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight pb-4 border-b border-slate-100">
          {titles[type]}
        </h1>

        {type === 'terms' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-900">1. Unified User Relationship</h2>
            <p>
              By accessing WorkSphere, users agree that all transactions, contracts, and proposals are conducted under a single, unified account identity. Users may act as both hiring clients and independent contractors without account bifurcation.
            </p>

            <h2 className="text-lg font-bold text-slate-900">2. Authoritative Double-Entry Ledger</h2>
            <p>
              All monetary interactions, escrow deposits, release transactions, and platform fees are recorded on an immutable double-entry ledger. Mathematical reconciliation is continuously enforced.
            </p>

            <h2 className="text-lg font-bold text-slate-900">3. Non-Circumvention</h2>
            <p>
              Parties who meet via WorkSphere agree to process all contract funding and deliverables exclusively through the WorkSphere Escrow and WorkStream platform for a period of 24 months.
            </p>
          </div>
        )}

        {type === 'privacy' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-900">1. Information Collection & Usage</h2>
            <p>
              WorkSphere collects account information, verification credentials, and financial transaction records strictly for contract execution, fraud prevention, and regulatory compliance.
            </p>

            <h2 className="text-lg font-bold text-slate-900">2. Data Security & Encryption</h2>
            <p>
              All user data is stored within hardened Google Cloud Run containerized infrastructure with AES-256 encryption at rest and TLS 1.3 in transit.
            </p>
          </div>
        )}

        {type === 'dispute-policy' && (
          <div className="space-y-4">
            <h2 className="text-lg font-bold text-slate-900">1. Ground for Arbitration</h2>
            <p>
              Either counterparty may initiate a formal dispute if deliverables fail to conform to the contract scope or if unilateral non-responsiveness occurs.
            </p>

            <h2 className="text-lg font-bold text-slate-900">2. Binding Administrative Resolution</h2>
            <p>
              Assigned Platform Arbitrators have full authority to examine project communications, code commits, and files to allocate escrow funds. Ledger entries generated by arbitration rulings are final.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
